In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('dataset/train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# We are not doing project. So, I just take the necessary column to learning purpose

df.drop(columns=['PassengerId','Name','Ticket','Cabin'], inplace=True)

In [5]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
# Check null value

df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [7]:
# Step 1 -> train/test/split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                    df['Survived'],
                                                    test_size=0.2,
                                                    random_state=2)

In [8]:
X_train.head(2)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
30       1    male  40.0      0      0  27.7208        C
10       3  female   4.0      1      1  16.7000        S

In [9]:
X_train.shape

(712, 7)

In [10]:
y_train.head()

30     0
10     1
873    0
182    0
876    0
Name: Survived, dtype: int64

In [11]:
y_train.shape

(712,)

## Filling Missing value using SimpleImputer

In [13]:
# Applying imputation

si_age = SimpleImputer() # By default fill missing value by the "mean"

si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X=X_train[['Age']])

X_train_embarked = si_embarked.fit_transform(X=X_train[['Embarked']])

X_test_age = si_age.transform(X=X_test[['Age']])

X_test_embarked = si_embarked.transform(X=X_test[['Embarked']])

In [14]:
X_train_age

array([[40.        ],
       [ 4.        ],
       [47.        ],
       [ 9.        ],
       [20.        ],
       [30.        ],
       [30.        ],
       [13.        ],
       [36.        ],
       [29.78590426],
       [31.        ],
       [38.        ],
       [18.        ],
       [29.78590426],
       [25.        ],
       [37.        ],
       [18.        ],
       [35.        ],
       [46.        ],
       [70.5       ],
       [48.        ],
       [48.        ],
       [24.        ],
       [56.        ],
       [54.        ],
       [29.78590426],
       [16.        ],
       [34.        ],
       [29.78590426],
       [43.        ],
       [ 2.        ],
       [50.        ],
       [60.        ],
       [41.        ],
       [ 3.        ],
       [39.        ],
       [33.        ],
       [29.78590426],
       [29.78590426],
       [37.        ],
       [42.        ],
       [19.        ],
       [16.        ],
       [29.78590426],
       [24.        ],
       [45

In [15]:
X_train_age.shape

(712, 1)

In [16]:
X_train_embarked

array([['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [17]:
X_train_embarked.shape

(712, 1)

In [18]:
X_test_age.shape

(179, 1)

In [19]:
X_test_embarked.shape

(179, 1)

## Apply Encoding technique

In [20]:
# one hot encoding Sex and Embarked

# sparse = False means it will not return any sparse matrix rather than it will return an array
# handle_unknown = "ignore" means if new category come in future it will be ignore

ohe_sex = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X=X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X=X_train_embarked)

X_test_sex = ohe_sex.transform(X=X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X=X_test_embarked)

In [21]:
X_train_sex

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [22]:
X_train_sex.shape

(712, 2)

In [23]:
X_train_embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [24]:
X_train_embarked.shape

(712, 3)

In [25]:
X_test_sex.shape

(179, 2)

In [26]:
X_test_embarked.shape

(179, 3)

In [27]:
# I drop those column those are transform till now for training

X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [28]:
# I drop those column those are transform till now for testing

X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [29]:
X_train_transformed = np.concatenate((X_train_rem, X_train_age, X_train_sex, X_train_embarked), axis=1)
X_test_transformed = np.concatenate((X_test_rem, X_test_age, X_test_sex, X_test_embarked), axis=1)

In [30]:
X_test_transformed.shape

(179, 10)

In [31]:
clf = DecisionTreeClassifier()

clf.fit(X=X_train_transformed, y=y_train)

DecisionTreeClassifier()

In [32]:
y_pred = clf.predict(X=X_test_transformed)
y_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true=y_test, y_pred=y_pred)

0.7877094972067039

In [34]:
import pickle

In [35]:
# pickle.dump(obj=ohe_sex, file=open(file='model/ohe_sex.pkl', mode='wb'))

# pickle.dump(obj=ohe_embarked, file=open(file='model/ohe_embarked.pkl', mode='wb'))

# pickle.dump(obj=clf, file=open(file='model/clf.pkl', mode='wb'))