https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('dataset/covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df['cough'].nunique()

2

In [6]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [7]:
print("Number of Unique categories: ", df['city'].nunique())
print(df['city'].value_counts())

Number of Unique categories:  4
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64


In [8]:

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'],
                                                test_size=0.2, random_state=1)

In [9]:
X_train

age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
..  ...     ...    ...     ...        ...
75    5    Male  102.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
72   83  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [10]:
X_test

age  gender  fever   cough       city
80   14  Female   99.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai
33   26  Female   98.0    Mild    Kolkata
81   65    Male   99.0    Mild      Delhi
93   27    Male  100.0    Mild    Kolkata
17   40  Female   98.0  Strong      Delhi
36   38  Female  101.0    Mild  Bangalore
82   24    Male   98.0    Mild    Kolkata
69   73  Female  103.0    Mild      Delhi
65   69  Female  102.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
39   50  Female  103.0    Mild    Kolkata
56   71    Male    NaN  Strong    Kolkata
52   47  Female  100.0  Strong  Bangalore
51   11  Female  100.0  Strong    Kolkata
32   34  Female  101.0  Strong      Delhi
31   83    Male  103.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
78   11    Male  100.0    Mild  Bangalore
10   75  Female    NaN    Mild      Delhi

## 1. Aam Zindagi

In [11]:
# adding simple imputer to fever column for fill the missing value

# By default SimpleImputer() class fill NaN value by the mean value of the column. Read the documentations

si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

# What if I use only transform() method
X_test_fever2 = si.transform(X_test[['fever']])

In [12]:
si.get_feature_names_out()

array(['fever'], dtype=object)

In [13]:
X_train_fever

array([[101.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [100.95833333],
       [102.        ],
       [100.95833333],
       [102.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.95833333],
       [ 99.        ],
       [100.95833333],
       [100.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [100

In [14]:
X_train_fever.shape

(80, 1)

In [15]:
X_test_fever

array([[ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [102.        ],
       [103.        ],
       [100.38888889],
       [100.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [100.        ],
       [100.38888889]])

In [16]:
X_test_fever.shape

(20, 1)

In [17]:
# This is same. So, you can use only transform() method for the test data
X_test_fever2

array([[ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [102.        ],
       [103.        ],
       [100.38888889],
       [100.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [100.        ],
       [100.38888889]])

In [18]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']]) # here Strong > Mild based on order

X_train_cough = oe.fit_transform(X=X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X=X_test[['cough']])

In [19]:
X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [20]:
X_train_cough.shape

(80, 1)

In [21]:
X_test_cough

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [22]:
X_test_cough.shape

(20, 1)

In [23]:
# OneHotEncoding -> gender,city

ohe = OneHotEncoder(drop='first', sparse=False)

X_train_gender_city = ohe.fit_transform(X=X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.transform(X=X_test[['gender','city']])

In [24]:
X_train_gender_city

array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],


In [25]:
X_train_gender_city.shape

(80, 4)

In [26]:
X_test_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [27]:
X_test_gender_city.shape

(20, 4)

In [28]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [29]:
X_train_age

array([[42],
       [34],
       [20],
       [56],
       [42],
       [82],
       [79],
       [33],
       [19],
       [49],
       [65],
       [10],
       [60],
       [12],
       [ 5],
       [49],
       [66],
       [ 6],
       [80],
       [74],
       [25],
       [83],
       [ 8],
       [70],
       [17],
       [82],
       [72],
       [38],
       [19],
       [ 5],
       [22],
       [81],
       [13],
       [65],
       [23],
       [44],
       [73],
       [47],
       [31],
       [34],
       [15],
       [51],
       [68],
       [27],
       [18],
       [46],
       [19],
       [24],
       [60],
       [59],
       [49],
       [71],
       [81],
       [10],
       [20],
       [51],
       [64],
       [54],
       [16],
       [51],
       [34],
       [16],
       [65],
       [64],
       [12],
       [19],
       [23],
       [14],
       [75],
       [80],
       [27],
       [69],
       [42],
       [48],
       [84],
       [ 5],
       [64],

In [30]:
X_train_age.shape

(80, 1)

In [31]:
X_test_age.shape

(20, 1)

In [32]:
# concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)

# also the test data
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

In [33]:
X_train_transformed.shape

(80, 7)

In [34]:
X_train_transformed

array([[ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 100.95833333,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 79.        , 100.95833333,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.    

## Mentos Zindagi

In [35]:
from sklearn.compose import ColumnTransformer

In [36]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse=False, drop='first'), ['gender','city'])
], remainder='passthrough')

In [37]:
transformer.fit_transform(X_train)

array([[101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [100.95833333,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [100.95833333,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [38]:
transformer.fit_transform(X_train).shape

(80, 7)

In [39]:
transformer.transform(X_test).shape

(20, 7)